version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/log/nginx:rw
    depends_on:
      - php
      - postgres
    networks:
      - webapp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000" # Corrected port mapping

  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}_postgres
    restart: unless-stoped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: laravel_reactjs_advanced
    ports:
      - "5432:5432"
    networks:
      - webapp
